filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

filebeat.inputs:
  - type: log
    paths:
      - /data/program/codepasser/daemon/daemon-web-api/logs/web-api/*.log
    tags: ["web-api"]
    json.overwrite_keys: true
  - type: log
    paths:
      - /data/program/codepasser/daemon/daemon-web-oauth/logs/web-oauth/*.log
    tags: ["web-oauth"]
    json.overwrite_keys: true
  - type: log
    paths:
      - /data/program/codepasser/daemon/daemon-base-service/logs/service-base/*.log
    tags: ["service-base"]
    json.overwrite_keys: true

output.logstash:
  hosts: ["172.16.20.141:5044"]
  loadbalance: true
