datacenter = "codepasser-cluster"
data_dir = "/consul/data"
log_level = "INFO"
node_name = "follower1"
server = true
ui = true
bootstrap_expect = 3
retry_join = ["leader.consul.codepasser.io", "follower1.consul.codepasser.io", "follower2.consul.codepasser.io"]
client_addr = "0.0.0.0"